<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ==================== Material 1: Pengenalan PBO ====================
            // Sub-material 1: Apa itu PBO?
            [
                'id'              => 1,
                'material_id'     => 1,
                'sub_material_id' => 1,
                'question_text'   => 'Apa yang dimaksud dengan Pemrograman Berorientasi Objek (PBO)?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang paradigma pemrograman yang menggunakan objek dan kelas',
                'created_by'      => 2,
            ],
            [
                'id'              => 2,
                'material_id'     => 1,
                'sub_material_id' => 1,
                'question_text'   => 'Apa kepanjangan dari OOP?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Ini adalah akronim bahasa Inggris untuk PBO',
                'created_by'      => 2,
            ],

            // Sub-material 2: Prinsip-Prinsip PBO
            [
                'id'              => 3,
                'material_id'     => 1,
                'sub_material_id' => 2,
                'question_text'   => 'Manakah yang BUKAN merupakan prinsip dari PBO?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Ingat empat pilar utama: Enkapsulasi, Pewarisan, Polimorfisme, dan Abstraksi',
                'created_by'      => 2,
            ],
            [
                'id'              => 4,
                'material_id'     => 1,
                'sub_material_id' => 2,
                'question_text'   => 'PBO membantu mengorganisir kode dengan mengelompokkan data dan _____ yang terkait bersama-sama.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Apa sebutan untuk tindakan atau perilaku dalam PBO?',
                'created_by'      => 2,
            ],
            [
                'id'              => 5,
                'material_id'     => 1,
                'sub_material_id' => 2,
                'question_text'   => 'Bahasa pemrograman mana yang mendukung PBO?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Sebagian besar bahasa pemrograman modern mendukung PBO',
                'created_by'      => 2,
            ],
            [
                'id'              => 6,
                'material_id'     => 1,
                'sub_material_id' => 2,
                'question_text'   => 'Empat prinsip utama PBO adalah: Enkapsulasi, Abstraksi, Pewarisan, dan _____.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Prinsip ini memungkinkan objek mengambil banyak bentuk',
                'created_by'      => 2,
            ],

            // ==================== Material 2: Kelas dan Objek ====================
            // Sub-material 3: Memahami Kelas
            [
                'id'              => 7,
                'material_id'     => 2,
                'sub_material_id' => 3,
                'question_text'   => 'Apa itu kelas dalam PBO?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang cetak biru atau template',
                'created_by'      => 2,
            ],
            [
                'id'              => 8,
                'material_id'     => 2,
                'sub_material_id' => 3,
                'question_text'   => 'Sebuah kelas adalah _____ untuk membuat objek.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang rencana arsitektur untuk membangun rumah',
                'created_by'      => 2,
            ],

            // Sub-material 4: Membuat Objek
            [
                'id'              => 9,
                'material_id'     => 2,
                'sub_material_id' => 4,
                'question_text'   => 'Apa itu objek dalam PBO?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Ini adalah perwujudan yang dibuat dari sebuah kelas',
                'created_by'      => 2,
            ],
            [
                'id'              => 10,
                'material_id'     => 2,
                'sub_material_id' => 4,
                'question_text'   => 'Kata kunci mana yang digunakan untuk membuat objek baru di Java?',
                'question_type'   => 'radio_button',
                'type'            => 'sintaks',
                'difficulty'      => 'beginner',
                'hint'            => 'Kata kunci bahasa Inggris yang berarti "baru"',
                'created_by'      => 2,
            ],
            [
                'id'              => 11,
                'material_id'     => 2,
                'sub_material_id' => 4,
                'question_text'   => 'Urutkan langkah-langkah untuk membuat dan menggunakan objek: [zone], [zone], [zone]',
                'question_type'   => 'drag_and_drop',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Pertama definisikan, lalu buat, akhirnya gunakan',
                'created_by'      => 2,
            ],
            [
                'id'              => 12,
                'material_id'     => 2,
                'sub_material_id' => 4,
                'question_text'   => 'Dapatkah sebuah kelas memiliki banyak objek?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang berapa banyak rumah yang bisa dibangun dari satu cetak biru',
                'created_by'      => 2,
            ],

            // Sub-material 5: Konstruktor dan Metode
            [
                'id'              => 13,
                'material_id'     => 2,
                'sub_material_id' => 5,
                'question_text'   => 'Apa itu konstruktor?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Ini adalah metode khusus yang menginisialisasi objek',
                'created_by'      => 2,
            ],
            [
                'id'              => 14,
                'material_id'     => 2,
                'sub_material_id' => 5,
                'question_text'   => 'Metode _____ dipanggil secara otomatis saat sebuah objek dibuat.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Memiliki nama yang sama dengan kelasnya',
                'created_by'      => 2,
            ],
            [
                'id'              => 15,
                'material_id'     => 2,
                'sub_material_id' => 5,
                'question_text'   => 'Apa itu atribut dalam sebuah kelas?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Mereka merepresentasikan status atau properti dari sebuah objek',
                'created_by'      => 2,
            ],

            // ==================== Material 3: Pewarisan ====================
            // Sub-material 6: Dasar-Dasar Pewarisan
            [
                'id'              => 16,
                'material_id'     => 3,
                'sub_material_id' => 6,
                'question_text'   => 'Apa itu pewarisan dalam PBO?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang bagaimana anak mewarisi sifat dari orang tua',
                'created_by'      => 2,
            ],
            [
                'id'              => 17,
                'material_id'     => 3,
                'sub_material_id' => 6,
                'question_text'   => 'Kelas yang mewarisi dari kelas lain disebut kelas _____.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Juga disebut sebagai subclass atau child class',
                'created_by'      => 2,
            ],
            [
                'id'              => 18,
                'material_id'     => 3,
                'sub_material_id' => 6,
                'question_text'   => 'Kelas induk juga dikenal dengan sebutan apa?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Dapat disebut base class atau istilah lain yang dimulai dengan "super"',
                'created_by'      => 2,
            ],

            // Sub-material 7: Mengimplementasikan Pewarisan
            [
                'id'              => 19,
                'material_id'     => 3,
                'sub_material_id' => 7,
                'question_text'   => 'Kata kunci apa yang digunakan di Java untuk mewarisi dari kelas induk?',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'sintaks',
                'difficulty'      => 'beginner',
                'hint'            => 'Kata kunci bahasa Inggris yang berarti "memperluas"',
                'created_by'      => 2,
            ],
            [
                'id'              => 20,
                'material_id'     => 3,
                'sub_material_id' => 7,
                'question_text'   => 'Kata kunci _____ digunakan untuk memanggil konstruktor kelas induk.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Kata kunci yang sama digunakan untuk merujuk ke parent class',
                'created_by'      => 2,
            ],
            [
                'id'              => 21,
                'material_id'     => 3,
                'sub_material_id' => 7,
                'question_text'   => 'Dapatkah subclass mengakses anggota privat dari superclass-nya?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Privat berarti sepenuhnya tersembunyi dari luar',
                'created_by'      => 2,
            ],

            // Sub-material 8: Jenis-Jenis Pewarisan
            [
                'id'              => 22,
                'material_id'     => 3,
                'sub_material_id' => 8,
                'question_text'   => 'Urutkan hierarki pewarisan: [zone], [zone], [zone]',
                'question_type'   => 'drag_and_drop',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Mulai dari yang paling umum ke yang paling spesifik',
                'created_by'      => 2,
            ],
            [
                'id'              => 23,
                'material_id'     => 3,
                'sub_material_id' => 8,
                'question_text'   => 'Jenis pewarisan apa yang TIDAK didukung Java secara langsung?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'hard',
                'hint'            => 'Java tidak mengizinkan sebuah kelas mewarisi dari banyak kelas sekaligus',
                'created_by'      => 2,
            ],

            // ==================== Material 4: Polimorfisme ====================
            // Sub-material 9: Konsep Polimorfisme
            [
                'id'              => 24,
                'material_id'     => 4,
                'sub_material_id' => 9,
                'question_text'   => 'Apa itu polimorfisme?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Kata tersebut berarti "banyak bentuk" dalam bahasa Yunani',
                'created_by'      => 2,
            ],
            [
                'id'              => 25,
                'material_id'     => 4,
                'sub_material_id' => 9,
                'question_text'   => 'Polimorfisme memungkinkan objek dari kelas yang berbeda diperlakukan sebagai objek dari kelas _____ yang sama.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'hard',
                'hint'            => 'Pikirkan tentang hierarki kelas - apa yang ada di atasnya?',
                'created_by'      => 2,
            ],

            // Sub-material 10: Method Overloading
            [
                'id'              => 26,
                'material_id'     => 4,
                'sub_material_id' => 10,
                'question_text'   => 'Jenis polimorfisme mana yang diselesaikan pada waktu kompilasi?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Terjadi selama kompilasi, bukan saat program berjalan',
                'created_by'      => 2,
            ],
            [
                'id'              => 27,
                'material_id'     => 4,
                'sub_material_id' => 10,
                'question_text'   => 'Method _____ memungkinkan beberapa metode dengan nama yang sama tetapi parameter berbeda.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Istilah bahasa Inggris yang berarti membebani secara berlebihan',
                'created_by'      => 2,
            ],

            // Sub-material 11: Method Overriding
            [
                'id'              => 28,
                'material_id'     => 4,
                'sub_material_id' => 11,
                'question_text'   => 'Apa itu method overriding?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Subclass menyediakan implementasi baru dari metode induknya',
                'created_by'      => 2,
            ],
            [
                'id'              => 29,
                'material_id'     => 4,
                'sub_material_id' => 11,
                'question_text'   => 'Anotasi mana yang digunakan untuk overriding metode di Java?',
                'question_type'   => 'radio_button',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Dimulai dengan @ dan menunjukkan Anda mengganti sebuah metode',
                'created_by'      => 2,
            ],
            [
                'id'              => 30,
                'material_id'     => 4,
                'sub_material_id' => 11,
                'question_text'   => 'Urutkan konsep polimorfisme berdasarkan waktu eksekusi: [zone], [zone]',
                'question_type'   => 'drag_and_drop',
                'type'            => 'teori',
                'difficulty'      => 'hard',
                'hint'            => 'Satu terjadi pada waktu kompilasi, satu pada waktu jalan (runtime)',
                'created_by'      => 2,
            ],

            // ==================== Material 5: Enkapsulasi ====================
            // Sub-material 12: Prinsip Enkapsulasi
            [
                'id'              => 31,
                'material_id'     => 5,
                'sub_material_id' => 12,
                'question_text'   => 'Apa itu enkapsulasi?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Ini tentang membungkus data dan metode bersama-sama',
                'created_by'      => 2,
            ],
            [
                'id'              => 32,
                'material_id'     => 5,
                'sub_material_id' => 12,
                'question_text'   => 'Apa manfaat utama dari enkapsulasi?',
                'question_type'   => 'radio_button',
                'type'            => 'teori',
                'difficulty'      => 'beginner',
                'hint'            => 'Pikirkan tentang melindungi data dan menyembunyikan implementasi',
                'created_by'      => 2,
            ],
            [
                'id'              => 33,
                'material_id'     => 5,
                'sub_material_id' => 12,
                'question_text'   => 'Enkapsulasi juga dikenal sebagai data _____.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'teori',
                'difficulty'      => 'medium',
                'hint'            => 'Tentang menjaga data tetap aman dan tersembunyi',
                'created_by'      => 2,
            ],

            // Sub-material 13: Modifier Akses
            [
                'id'              => 34,
                'material_id'     => 5,
                'sub_material_id' => 13,
                'question_text'   => 'Modifier akses _____ membuat variabel hanya dapat diakses dalam kelasnya sendiri.',
                'question_type'   => 'fill_in_the_blank',
                'type'            => 'sintaks',
                'difficulty'      => 'beginner',
                'hint'            => 'Ini adalah modifier akses yang paling ketat',
                'created_by'      => 2,
            ],
            [
                'id'              => 35,
                'material_id'     => 5,
                'sub_material_id' => 13,
                'question_text'   => 'Modifier akses mana yang memberikan pembatasan paling besar?',
                'question_type'   => 'radio_button',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Benar-benar menyembunyikan anggota dari luar kelas',
                'created_by'      => 2,
            ],
            [
                'id'              => 36,
                'material_id'     => 5,
                'sub_material_id' => 13,
                'question_text'   => 'Urutkan modifier akses dari yang paling ketat ke paling longgar: [zone], [zone], [zone], [zone]',
                'question_type'   => 'drag_and_drop',
                'type'            => 'sintaks',
                'difficulty'      => 'hard',
                'hint'            => 'private, default, protected, public',
                'created_by'      => 2,
            ],

            // Sub-material 14: Getter dan Setter
            [
                'id'              => 37,
                'material_id'     => 5,
                'sub_material_id' => 14,
                'question_text'   => 'Metode getter dan setter digunakan untuk apa?',
                'question_type'   => 'radio_button',
                'type'            => 'sintaks',
                'difficulty'      => 'medium',
                'hint'            => 'Mereka menyediakan akses terkontrol ke variabel privat',
                'created_by'      => 2,
            ],
        ];

        foreach ($questions as $question) {
            Question::updateOrCreate(
                ['id' => $question['id']],
                $question,
            );
        }
    }
}
