import os
import re
import json

WORKSPACE = os.getcwd()
CONSTANTS_PATH = os.path.join(WORKSPACE, 'app', 'Rules', 'Adaptive', 'Constants', 'AdaptiveConstants.php')
SERVICE_PATH = os.path.join(WORKSPACE, 'app', 'Services', 'Adaptive', 'FactGatheringService.php')
SEEDER_PATH = os.path.join(WORKSPACE, 'database', 'seeders', 'AdaptiveRuleSeeder.php')

def parse_constants():
    facts = {}
    actions = {}
    with open(CONSTANTS_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
        # FACT_XXX = 'Name'
        fact_matches = re.findall(r"public const (FACT_\w+)\s*=\s*'([^']+)'", content)
        for name, value in fact_matches:
            facts[name] = value
        
        # ACTION_XXX = 'Value'
        action_matches = re.findall(r"public const (ACTION_\w+)\s*=\s*'([^']+)'", content)
        for name, value in action_matches:
            actions[name] = value
    return facts, actions

def parse_produced_facts():
    produced = set()
    with open(SERVICE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
        matches = re.findall(r"AdaptiveConstants::(FACT_\w+)", content)
        for m in matches:
            produced.add(m)
    return produced

def parse_seeder():
    # This is a bit tricky as it's PHP code. I'll use regex for the basic structure.
    facts_seeded = {} # code -> name_constant
    rules = [] # list of rules
    
    with open(SEEDER_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
        
        # 1. Parse Facts Seeded
        # ['code' => 'G01', ..., 'name' => AC::FACT_SCORE_FAILURE, ...]
        fact_block_match = re.search(r"\$facts = \[(.*?)\];", content, re.DOTALL)
        if fact_block_match:
            block = fact_block_match.group(1)
            entries = re.findall(r"\['code'\s*=>\s*'([^']+)',.*?'name'\s*=>\s*AC::(FACT_\w+)", block)
            for code, name in entries:
                facts_seeded[code] = name
        
        # 2. Parse Rules Seeded
        # ['code' => 'R01', 'name' => '...', 'priority' => 1, 'required' => ['G03', ...], 'forbidden' => [...], 'action' => 'H18']
        rule_block_match = re.search(r"\$rules = \[(.*?)\];", content, re.DOTALL)
        if rule_block_match:
            block = rule_block_match.group(1)
            # Find each array entry
            rule_entries = re.findall(r"\[(.*?)\]", block, re.DOTALL)
            for entry in rule_entries:
                code_m = re.search(r"'code'\s*=>\s*'([^']+)'", entry)
                name_m = re.search(r"'name'\s*=>\s*'([^']+)'", entry)
                priority_m = re.search(r"'priority'\s*=>\s*(\d+)", entry)
                action_m = re.search(r"'action'\s*=>\s*'([^']+)'", entry)
                
                required_m = re.search(r"'required'\s*=>\s*\[(.*?)\]", entry)
                required = []
                if required_m:
                    required = re.findall(r"'([^']+)'", required_m.group(1))
                elif "'required' => null" in entry:
                    required = []
                
                forbidden_m = re.search(r"'forbidden'\s*=>\s*\[(.*?)\]", entry)
                forbidden = []
                if forbidden_m:
                    forbidden = re.findall(r"'([^']+)'", forbidden_m.group(1))
                
                if code_m:
                    rules.append({
                        'code': code_m.group(1),
                        'name': name_m.group(1) if name_m else "Unknown",
                        'priority': int(priority_m.group(1)) if priority_m else 0,
                        'required': required,
                        'forbidden': forbidden,
                        'action_code': action_m.group(1) if action_m else "H00"
                    })
    return facts_seeded, rules

def main():
    fac_const, act_const = parse_constants()
    produced = parse_produced_facts()
    seeded_facts, rules = parse_seeder()
    
    print("# Oopedia Adaptive Rule Engine Audit Report\n")
    
    # --- 1. Fact Consistency ---
    print("## 1. Fact Consistency Analysis")
    
    # Facts produced in Service but not in Constants (shouldn't happen with regex used)
    # Facts produced in Service but not Seeded in DB
    seeded_const_names = set(seeded_facts.values())
    not_seeded = [p for p in produced if p not in seeded_const_names]
    
    if not_seeded:
        print("\n### ⚠️ Missing Fact Seedings (Produced but NOT in Seeder)")
        print("These facts are generated by `FactGatheringService` but are not present in the `adaptive_facts` table via Seeder.")
        for p in not_seeded:
            print(f"- `{p}` (Value: '{fac_const.get(p, 'MISSING_IN_CONSTANTS')}')")
    else:
        print("\n- ✅ All produced facts are correctly seeded in the database.")
        
    # --- 2. Rule Logic Integrity ---
    print("\n## 2. Rule Logic Integrity")
    
    # Check for invalid fact codes in rules (like G32)
    seeded_codes = set(seeded_facts.keys())
    bad_codes = set()
    for rule in rules:
        for code in rule['required'] + rule['forbidden']:
            if code not in seeded_codes:
                bad_codes.add(code)
                print(f"- ❌ Rule `{rule['code']}` (`{rule['name']}`) uses undefined fact code: `{code}`")
    
    if not bad_codes:
        print("- ✅ All rules use valid fact codes defined in the seeder.")
        
    # Check for dead rules (rules requiring facts that are NEVER produced)
    seeded_fact_to_const = {code: name for code, name in seeded_facts.items()}
    for rule in rules:
        unproduced = []
        for code in rule['required']:
            const_name = seeded_fact_to_const.get(code)
            if const_name and const_name not in produced:
                unproduced.append(f"{code} ({const_name})")
        if unproduced:
            print(f"- ℹ️ Rule `{rule['code']}` (`{rule['name']}`) requires unproduced facts: {', '.join(unproduced)}")
            print(f"  *This rule might be dead unless these facts are produced elsewhere.*")

    # --- 3. Priority & Collision Analysis ---
    print("\n## 3. Priority & Action Analysis")
    
    priorities = {}
    for rule in rules:
        p = rule['priority']
        if p in priorities:
            priorities[p].append(rule['code'])
        else:
            priorities[p] = [rule['code']]
            
    collisions = {p: codes for p, codes in priorities.items() if len(codes) > 1}
    if collisions:
        print("\n### ⚠️ Priority Collisions (Deterministic Risks)")
        for p, codes in collisions.items():
            print(f"- Priority `{p}`: Rules {', '.join(codes)}")
    else:
        print("- ✅ All rules have unique priorities.")

    # --- 4. Dead Facts (Produced but Never Consumed) ---
    print("\n## 4. Optimization Recommendations")
    
    consumed_codes = set()
    for rule in rules:
        for code in rule['required'] + rule['forbidden']:
            consumed_codes.add(code)
            
    unused_produced_codes = []
    for code, name in seeded_facts.items():
        if name in produced and code not in consumed_codes:
            unused_produced_codes.append(f"{code} ({name})")
            
    if unused_produced_codes:
        print("\n### ℹ️ Unused Produced Facts")
        print("These facts are generated but no rule handles them:")
        for f in unused_produced_codes:
            print(f"- {f}")
    
    print("\n### 📝 Detailed Recommendations")
    if not_seeded or bad_codes:
        print("1. **Urgent**: Synchronize `AdaptiveRuleSeeder.php` with `FactGatheringService.php`. Add missing G-codes (G31, G32, etc.) for `FACT_SATISFACTORY_PROGRESS`, `FACT_DIFF_MEDIUM`, etc.")
        print("2. **Fix**: Update Rule `R05` and `R16` to use the correct seeded code for `Satisfactory Progress` once added.")
        print("3. **Cleanup**: Remove references to `G24` if it's no longer used or needed.")

if __name__ == "__main__":
    main()
