name: CI/CD Pipeline Rey-Oopedia

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        uses: ./.github/workflows/build.yml

    security:
        uses: ./.github/workflows/security.yml
        permissions:
            contents: read
            issues: write
        secrets: inherit

    deploy:
        needs: [build, security]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/workflows/deploy.yml
        secrets:
            SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            SERVER_USER: ${{ secrets.SERVER_USER }}
